[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "minio>=7.2.20",
    "psycopg[binary]>=3.3.5",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]