version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecom_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: electronics_store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecom-net

  backend:
    build: ./backend
    container_name: ecom_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/electronics_store
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=electronics
      - MINIO_USE_SSL=false
    depends_on:
      - db
    networks:
      - ecom-net

  frontend:
    build: ./frontend
    container_name: ecom_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecom-net

volumes:
  pgdata:

networks:
  ecom-net:
    driver: bridge